gbifapi/gbifapi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("speciesdiversity/", include("speciesdiversity.urls")),
    path('admin/', admin.site.urls),
]

gbifapi/speciesdiversity/urls.py
from django.urls import path
from . import views

app_name = 'speciesdiversity'
urlpatterns = [
    path("", views.index, name="index"),
    path('speciesdiversity/', views.speciesdiversity, name='speciesdiversity'),
    path('speciesdata/<str:country_code>/', views.species_data_view, name='species_data'),
    path('species_data_view/', views.species_data_view, name='species_data_view'),

]

gbifapi/speciesdiversity/models.py
from django.db import models

# Almacenamos aquí los países a elegir
class Country(models.Model):
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=2)

    def __str__(self):
        return self.name


class Graphs(models.Model):
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    data_value = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Diversidad y riqueza en {self.country}"

gbifapi/speciesdiversity/views.py
from django.shortcuts import render
import requests
from collections import Counter
import math
import matplotlib.pyplot as plt
import os

def speciesdiversity(request):
    countries = get_country_list()
    return render(request, 'speciesdiversity/country_selection.html', {'countries': countries})


def get_country_list():
    url = "https://api.gbif.org/v1/enumeration/country"
    response = requests.get(url)
    if response.status_code == 200:
        raw_countries = response.json()
        countries = [{'title': country['title'], 'iso2': country['iso2']} for country in raw_countries]
        return countries
    else:
        return []


def index(request):
    countries = get_country_list()
    selected_country = request.GET.get('country')  # Obtener el valor de country desde la URL
    if selected_country:
        species_data, total_records = get_species_data(selected_country)
        if species_data:
            species_abundances = Counter(species_data)
            diversity_index, richness_index = calculate_diversity_indexes(species_abundances)
            context = {
                'countries': countries,
                'species_abundances': species_abundances,
                'total_records': total_records,
                'diversity_index': diversity_index,
                'richness_index': richness_index,
                'selected_country': selected_country  # Pasar el valor de country a la plantilla
            }
            bar_chart_view(request, species_abundances)
            return render(request, 'speciesdiversity/main_page.html', context)

    return render(request, 'speciesdiversity/main_page.html', {'countries': countries})


def get_species_data(country_code):
    url = f"https://api.gbif.org/v1/occurrence/search?country={country_code}&limit=5000"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        species_list = [record.get('species') for record in data.get('results', []) if 'species' in record]
        total_records = len(species_list)
        return species_list, total_records
    else:
        return [], 0


def calculate_diversity_indexes(species_abundances): # Función para calcular índices de diversidad
    total_records = sum(species_abundances.values())
    shannon_index = 0
    simpson_index = 0

    for species_abundance in species_abundances.values(): # Calculamos el índice de Shannon
        pi = species_abundance / total_records # Primero sacando la proporción total de abundancia de N
        shannon_index += pi * math.log(pi) # Luego, por cada especie se multiplica la proporción por el ln

    shannon_index = -shannon_index # Guardamos el resultado y lo convertimos para legibilizar

    for species_abundance in species_abundances.values():
        pi = species_abundance / total_records
        simpson_index += pi ** 2

    simpson_index = 1 / simpson_index
    return shannon_index, simpson_index


def species_data_view(request):
    selected_country = request.GET.get('country')
    countries = get_country_list()
    diversity_index = 0
    richness_index = 0
    species_abundances = {}  # Diccionario para almacenar las abundancias de especies
    total_records = 0

    if selected_country:
        species_data, total_records = get_species_data(selected_country)
        if species_data:
            species_abundances = dict(Counter(species_data))  # Obtener el Counter como diccionario
            print("Species Abundances:", species_abundances)
            diversity_index, richness_index = calculate_diversity_indexes(species_abundances)

    # print("Antes de pasar el contexto:", type(species_abundances)) Debug para encontrar tipo de datos
    context = {
        'countries': countries,
        'species_abundances': species_abundances,
        'total_records': total_records,
        'diversity_index': diversity_index,
        'richness_index': richness_index,
        'selected_country': selected_country
    }
    # print("Después de pasar el contexto:", type(context['species_abundances']))

    bar_chart_view(request, species_abundances)
    return render(request, 'speciesdiversity/main_page.html', context)


def bar_chart_view(request, species_abundances):
    species_names = list(species_abundances.keys())
    abundances = list(species_abundances.values())

    plt.figure(figsize=(20, 12))
    plt.bar(species_names, abundances)
    plt.xlabel('Especies')
    plt.ylabel('Abundancia')
    plt.title('Gráfica de Abundancia de Especies')
    plt.xticks(ticks=[], labels=[])

    # Obtener la ruta completa para guardar la imagen en la carpeta static
    image_filename = 'grafica.png'
    image_path = os.path.join('speciesdiversity/static/speciesdiversity', image_filename)

    # Guardar la imagen en la ruta
    plt.savefig(image_path, format='png')
    plt.close()





gbifapi/speciesdiversity/templates/speciesdiversity/country_selection.html
<html>
<head>
    <title>Selección de país</title>
</head>
<body>
    <h1>Seleccione un país</h1>
    <form method="get" action="{% url 'speciesdiversity:species_data_view' %}">
    <select name="country">
    {% for country in countries %}
        <option value="{{ country.iso2 }}">{{ country.title }}</option>
    {% endfor %}
    </select>
    <button type="submit">Ver Resultados</button>
    </form>
</body>
</html>

gbifapi/speciesdiversity/templates/speciesdiversity/main_page.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Página de app</title>
     <link rel="stylesheet" type="text/css" href="/static/speciesdiversity/styles.css">
</head>
<body>
    <header>Diversidad de especies por país</header>

    <section>
        {% block country_selection %}
            {% include 'speciesdiversity/country_selection.html' with countries=countries %}
        {% endblock %}
    </section>

   <section>
    {% if selected_country and species_abundances %}
        <h2>Resultados de especies de {{ selected_country }}</h2>
        <table>
            <tr>
                <th>Especie</th>
                <th>Abundancia</th>
            </tr>
            {% for species, abundance in species_abundances.items %}
            <tr>
                <td>{{ species }}</td>
                <td>{{ abundance }}</td>
            </tr>
        {% endfor %}



        </table>
    {% endif %}
</section>

    <section>
        {% if selected_country %}
        <table>
            <tr>
                <th>N Población total: {{ total_records }}</th>
                <th>Índice de Shannon: {{ diversity_index }}</th>
                <th>Índice de Simpson: {{ richness_index }}</th>
            </tr>

        </table>
        {% endif %}
    </section>

  <section>
    {% if selected_country %}
        <img class="centered-image" src="{% static 'grafica.png' %}" alt="Gráfica de Barras">
    {% endif %}
</section>


</body>
</html>

gbifapi/speciesdiversity/templates/speciesdiversity/templatetest.html
<html>
<h1>Species Diversity html test</h1>
<body>

<p>Esto es una prueba</p>

</body>

</html>